-- ***************************** SqlDBM: MySQL ****************************
-- * Generated by SqlDBM:  Project-1, v19 by raghav.gupta@zemosolabs.com *

create database hotel;
use hotel;


-- ************************************** `Customer`

CREATE TABLE `Customer`
(
 `CustID` numeric NOT NULL ,
 `Name`   varchar(45) NOT NULL ,
 `Age`    varchar(45) NOT NULL ,
 `Phone`  numeric(10) NOT NULL ,
 `Email`  varchar(45) NULL ,

PRIMARY KEY (`CustID`)
);






-- ************************************** `Hotel`

CREATE TABLE `Hotel`
(
 `HotelID`      int NOT NULL ,
 `HotelName`    varchar(45) NOT NULL ,
 `TotalRooms`   numeric NOT NULL ,
 `Desciription` varchar(45) NOT NULL ,
 `City`         varchar(45) NOT NULL ,

PRIMARY KEY (`HotelID`)
);







-- ************************************** `Reserved`

CREATE TABLE `Reserved`
(
 `Reserved_ID`      int NOT NULL ,
 `CustID`           numeric NOT NULL ,
 `Arrival`          timestamp NOT NULL ,
 `Departure`        timestamp NOT NULL ,
 `Discount_Percent` decimal(5,2) NOT NULL ,
 `Final_Price`      numeric NOT NULL ,

PRIMARY KEY (`Reserved_ID`),
KEY `FK_206` (`CustID`),
CONSTRAINT `FK_204` FOREIGN KEY `FK_206` (`CustID`) REFERENCES `Customer` (`CustID`)
);







-- ************************************** `RoomType`

CREATE TABLE `RoomType`
(
 `Room_Type_ID` int NOT NULL ,
 `Room_Type`    varchar(128) NOT NULL ,

PRIMARY KEY (`Room_Type_ID`)
);











-- ************************************** `Room`

CREATE TABLE `Room`
(
 `RoomID`       int NOT NULL ,
 `Floor_No`     int NOT NULL ,
 `Room_Type_ID` int NOT NULL ,
 `HotelID`      int NOT NULL ,
 `Price`        decimal(10,2) NOT NULL ,

PRIMARY KEY (`RoomID`),
KEY `FK_305` (`HotelID`),
CONSTRAINT `FK_303` FOREIGN KEY `FK_305` (`HotelID`) REFERENCES `Hotel` (`HotelID`),
KEY `FK_311` (`Room_Type_ID`),
CONSTRAINT `FK_309` FOREIGN KEY `FK_311` (`Room_Type_ID`) REFERENCES `RoomType` (`Room_Type_ID`)
);









-- ************************************** `Room_Reserved`

CREATE TABLE `Room_Reserved`
(
 `ID`          numeric NOT NULL ,
 `RoomID`      int NOT NULL ,
 `Reserved_ID` int NOT NULL ,
 `Price`       decimal(10,2) NOT NULL ,

PRIMARY KEY (`ID`),
KEY `FK_320` (`Reserved_ID`),
CONSTRAINT `FK_318` FOREIGN KEY `FK_320` (`Reserved_ID`) REFERENCES `Reserved` (`Reserved_ID`),
KEY `FK_532` (`RoomID`),
CONSTRAINT `FK_530` FOREIGN KEY `FK_532` (`RoomID`) REFERENCES `Room` (`RoomID`)
);




















